[phases.setup]
nixPkgs = ['php83', 'php83Extensions.pdo', 'php83Extensions.pdo_sqlite', 'php83Extensions.mbstring', 'php83Extensions.xml', 'php83Extensions.curl', 'php83Extensions.tokenizer', 'php83Extensions.dom', 'php83Extensions.fileinfo', 'php83Extensions.ctype', 'nodejs_20']

[phases.install]
cmds = ['cp .env.example .env', 'composer install --no-dev --optimize-autoloader --no-interaction', 'npm install', 'npm run build']

[variables]
APP_KEY = "base64:w6tw/F3clxp0gcuxJoTvvcXA6/ZcDIk8vaISdhrBZX4="
APP_ENV = "production"
APP_DEBUG = "true"
DB_CONNECTION = "sqlite"
DB_DATABASE = "/app/database/database.sqlite"

[start]
cmd = 'mkdir -p /app/storage/framework/sessions /app/storage/framework/views /app/storage/framework/cache/data /app/storage/logs /app/bootstrap/cache && chmod -R 775 /app/storage /app/bootstrap/cache && touch /app/database/database.sqlite && php artisan config:clear && php artisan cache:clear && php artisan view:clear && php artisan route:clear && php artisan migrate --force --seed && php artisan serve --host=0.0.0.0 --port=${PORT:-8000}'
